= Sweet Tooth =
Daniel Higginbotham




== What is Sweet Tooth? ==
My dream for Sweet Tooth is to make it easier, faster, and funner for developers
like you to get your ideas into production.

Swet Tooth does this by giving you the tools to deal with common SPA concerns
like handling forms, configuring routing and navigation, and managing API calls.
These use cases are not particular to the app you're trying to build, but as a
Clojurian you've likely had to figure them out for yourself when building an
SPA. In the same way that you shouldn't have to write your own filesystem when
making a desktop app, you shouldn't have to write your own form handling system
to launch your cool idea. (BTW - word on the street is in the 80's a new OS
would the street https://twitter.com/GeePawHill/status/1256342997643526151[every month or so], supporting my thesis that operating systems
are frameworks.)

I've tried to write Sweet Tooth so that using it doesn't lock you into some
weird, arcane world the way some frameworks do. It's built on top of popular and
proven libraries like re-frame, duct, integrant, liberator, ring, and reitit,
and you can always use those libraries directly if you need to.

The analogy I've had in mind is taken from the way we use files: files can be
structured as text, text can be structured as JSON, and JSON can be structured
as transit. Each additional degree of structure gives you added power while
requiring more special-purpose tools. Your XML tools won't work on a JSON file.
However, you can still use the lower-level tools; `sed` and `awk` work just
fine. For more on my underlying approach to framework development, see
http://flyingmachinestudios.com/programming/why-programmers-need-frameworks/[Frameworks and Why (Clojure) Programmers Need Them]

Eventually, I'd like to make it dramatically easier for beginners to make cool
stuff and show it to their friends and family. For that reason, I haven't put
any effort into making use of tools like GraphQL which can be quite powerful but
harder for beginners to grok and which, in my opinion, many apps don't need.


== What isn't Sweet Tooth? ==
Sweet Tooth is not for creating server-rendered apps. It hasn't been used for
high-traffic projects, so it's currently not for that, either.
